# Generated by Django 3.0.8 on 2020-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_produto_produtofornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedores',
            field=models.ManyToManyField(related_name='produto_fornecedor', to='demoapp.ProdutoFornecedor', verbose_name='Fornecedores'),
        ),
    ]
