# Generated by Django 3.0.8 on 2020-07-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_produto_fornecedores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedores',
            field=models.ManyToManyField(blank=True, related_name='produto_fornecedor', to='demoapp.ProdutoFornecedor', verbose_name='Fornecedores'),
        ),
    ]
