# Generated by Django 3.0.8 on 2020-07-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_auto_20200722_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Tipo atividade:')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escola.Aluno', verbose_name='Aluno')),
            ],
        ),
    ]
