# Generated by Django 3.0.8 on 2020-07-22 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alunoatividade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='disciplinas',
        ),
    ]
